name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: archchem
  REPO_NAME: dailybible-rs

jobs:
  build-and-push:
    runs-on: Ubuntu-20.04
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Build and push the image
        uses: docker/build-push-action@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
